tests = [ {'description': 'First test. Testing example 1',
    'steps': [ {'inputs': [('PINA',0x03)], 'iterations': 5 } ],
    'expected': [('PORTC',0x70)],
    },
    {'description': 'Second test. Testing example 2',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x40)],
    },
    {'description': 'Third test. Testing example 3',
    'steps': [ {'inputs': [('PINA',0xFF)], 'iterations': 5 } ],
    'expected': [('PORTC',0x3F)],
    },
	{'description': '4th test. Testing example 4',
    'steps': [ {'inputs': [('PINA',0xF3)], 'iterations': 5 } ],
    'expected': [('PORTC',0x70)],
    },
    {'description': '5th test. Testing example 5',
    'steps': [ {'inputs': [('PINA',0x30)], 'iterations': 5 } ],
    'expected': [('PORTC', 0xC0)],
    },
    ]
#watch = ['PORTB']

